# .github/ISSUE_TEMPLATE/feature-request.yml
name: "Feature request"
description: "Suggest a new feature or improvement for the extension"
title: "[FEATURE] "
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Describe the feature
        A clear and concise description of the functionality you’d like to see.
  - type: input
    id: user_story
    attributes:
      label: "User story"
      description: "As a <type of user>, I want to <action> so that <benefit>."
      placeholder: "e.g., As a new user, I want guided review intervals to retain concepts."
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: "Use case"
      description: "How and why you would use this feature"
      placeholder: "Describe a scenario where this feature helps."
    validations:
      required: true
  - type: textarea
    id: implementation_details
    attributes:
      label: "Implementation details (optional)"
      description: "Any API/UI suggestions or mockups"
      placeholder: "Sketches, links, or high-level ideas"
